Check in to avoid unneccessary trouble.

diff --git a/debian/piradio.postinst b/debian/piradio.postinst
--- a/debian/piradio.postinst
+++ b/debian/piradio.postinst
@@ -3,20 +3,66 @@
 # $Id: piradio.postinst,v 1.13 2014/07/21 07:56:34 bob Exp $
 
 # File locations
-DIR=/home/pi/radio
+DIR=/usr/share/piradio
 RADIOLIB=/var/lib/radiod
 INITTAB=/etc/inittab
 BOOTCMD=/boot/cmdline.txt 
 MODULES=/etc/modules
 MPDCONF=/etc/mpd.conf
 PODCASTSDIST=podcasts.dist
+LOGDIR=/var/log
+
+
+
+set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+case "$1" in
+    configure)
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+	exit 0
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
 
 # Display types
+db_get piradio/selectlcd
+echo "LCD = $RET"
+db_get piradio/selectuser
+echo "user = $RET"
+db_get piradio/selectgroup
+echo "group = $RET"
+exit 1
 LCD=3   # LCD screen (direct)
 ADA=4   # Adafruit LCD plate
+PIFACE=5 # Piface Control & Display
 
 echo "Executing post install script ${0}"
-update-rc.d -f radiod defaults
+update-rc.d -f piradio defaults
 sudo mkdir -p ${DIR}/playlists
 sudo chown -R pi:pi ${DIR}
 sudo chmod +x ${DIR}/*.py
@@ -57,6 +103,16 @@ elif [[ ${TYPE} -eq ${ADA} ]]; then
 		echo "# Original file stored as ${MODULES}.orig" >> ${MODULES} 
 		echo
 	fi
+elif [[ ${TYPE} -eq ${PIFACE} ]]; then
+	
+	if [[ ! -f   ${MODULES}.orig ]]; then
+		sudo cp -fp ${MODULES} ${MODULES}.orig
+		echo "spi-bcm2708" >>  ${MODULES}
+		echo "spi-dev" >>  ${MODULES}
+		echo "# Original file stored as ${MODULES}.orig" >> ${MODULES} 
+		echo
+	fi
+	REBOOT=1
 
 else 
 	echo "No radio daemon selected"
@@ -77,7 +133,7 @@ if [[ ! -f   ${MPDCONF}.orig ]]; then
 fi
 
 # Disable mpd on startup
-sudo update-rc.d mpd disable
+#sudo update-rc.d mpd disable
 
 # Go to radio directory
 cd ${DIR}
@@ -92,7 +148,7 @@ fi
 # Create playlists if no station list present
 if [[ ! -f "${RADIOLIB}/stationlist" ]]; then
 	echo "Creating playlists:"
-	${DIR}/create_playlists.py --no_delete 2>&1 > ${DIR}/playlists.log
+	${DIR}/create_playlists.py --no_delete 2>&1 > ${LOGDIR}/playlists.log
 	echo "See ${DIR}/playlists.log for information about playlists created"
 	echo
 fi
@@ -100,7 +156,7 @@ fi
 # End of installation
 echo
 echo "PI Radio software successfully installed"
-echo "See /usr/share/doc/radiod/README for release information"
+echo "See /usr/share/doc/piradio/README for release information"
 echo
 
 if [[ ${TYPE} -eq ${ADA} ]]; then
